name: Playwright Tests
on:
  push:
    branches: [ main, master ]
 
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install rimraf
      run: npm install rimraf  
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test:test2
        
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: stg-playwright-report
        path: playwright-report/
        retention-days: 10